version: '3'

services:
  app:
    container_name: my-node-app_app-service
    build: .
    command: wait-for database:3306 -t 40 -- yarn start
    ports:
      - 8080:3000
    volumes:
      - .:/my-simple-app/app
    depends_on:
      - database
    networks:
      - network
  
  database: 
    container_name: my-node-app_database-service
    image: mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
    networks:
      - network

networks:
  network:
    driver: bridge